In [9]:
import numpy as np
import pandas as pd
from numpy import array
from scipy.sparse import csr_matrix
from scipy.sparse import coo_matrix

In [3]:
number_user = 10
mu = np.zeros((number_user,))


(10,)

In [3]:
A = array([[1,0,0,1,0,0],[0,0,2,0,0,1],[0,0,0,2,0,0]])
print(A)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [4]:
S = csr_matrix(A)
S

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [5]:
print(S)

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [6]:
B =S.todense()

In [7]:
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [14]:
row = array([0,0,1,3,1,0,0])
col = array([0,2,1,3,1,0,0])
data = array([1,1,1,1,1,1,1])

A = coo_matrix((data,(row,col)), shape=(4,4)).tocsr()

  (0, 0)	3
  (0, 2)	1
  (1, 1)	2
  (3, 3)	1
