# MOVIE RECOMMENDER ENGINE

## Library

In [1]:
%matplotlib inline
import ast
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
import seaborn as sns
import operator
import collections


from IPython.display import Image, HTML, display
from scipy import stats
from ast import literal_eval
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import wordnet
from surprise.model_selection import cross_validate
from surprise import Reader, SVD, Dataset


import warnings; warnings.simplefilter('ignore')

## LOAD DataFrame

In [2]:
md = pd.read_csv('../the-movies-dataset/movies_metadata_equal_ratings_ver1.csv')
train = pd.read_csv('../the-movies-dataset/ratings_train.csv')

In [3]:
N = len(md)

In [4]:
N

9025

In [5]:
md.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9025 entries, 0 to 9024
Data columns (total 26 columns):
adult                    9025 non-null bool
belongs_to_collection    1670 non-null object
budget                   9025 non-null int64
genres                   9025 non-null object
homepage                 1954 non-null object
id                       9025 non-null int64
imdb_id                  9025 non-null object
original_language        9025 non-null object
original_title           9025 non-null object
overview                 9013 non-null object
popularity               9025 non-null float64
poster_path              9022 non-null object
production_companies     9025 non-null object
production_countries     9025 non-null object
release_date             9025 non-null object
revenue                  9025 non-null float64
runtime                  9025 non-null float64
spoken_languages         9025 non-null object
status                   9023 non-null object
tagline             

In [6]:
md.head().transpose()[:20]

0  \
adult                                                              False   
belongs_to_collection  {'id': 10194, 'name': 'Toy Story Collection', ...   
budget                                                          30000000   
genres                                 ['Animation', 'Comedy', 'Family']   
homepage                            http://toystory.disney.com/toy-story   
id                                                                   862   
imdb_id                                                        tt0114709   
original_language                                                     en   
original_title                                                 Toy Story   
overview               Led by Woody, Andy's toys live happily in his ...   
popularity                                                       21.9469   
poster_path                             /rhIRbceoE9lR4veEXuwCC2wARtG.jpg   
production_companies      [{'name': 'Pixar Animation Studios', 'id': 3}]   
production_countries   [{'iso_3166_1': 'US', 'name': 'United States o...   
release_date                                                  1995-10-30   
revenue                                                      3.73554e+08   
runtime                                                               81   
spoken_languages                [{'iso_639_1': 'en', 'name': 'English'}]   
status                                                          Released   
tagline                                                              NaN   

                                                                       1  \
adult                                                              False   
belongs_to_collection                                                NaN   
budget                                                          65000000   
genres                                ['Adventure', 'Fantasy', 'Family']   
homepage                                                             NaN   
id                                                                  8844   
imdb_id                                                        tt0113497   
original_language                                                     en   
original_title                                                   Jumanji   
overview               When siblings Judy and Peter discover an encha...   
popularity                                                       17.0155   
poster_path                             /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg   
production_companies   [{'name': 'TriStar Pictures', 'id': 559}, {'na...   
production_countries   [{'iso_3166_1': 'US', 'name': 'United States o...   
release_date                                                  1995-12-15   
revenue                                                      2.62797e+08   
runtime                                                              104   
spoken_languages       [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
status                                                          Released   
tagline                        Roll the dice and unleash the excitement!   

                                                                       2  \
adult                                                              False   
belongs_to_collection  {'id': 119050, 'name': 'Grumpy Old Men Collect...   
budget                                                                 0   
genres                                             ['Romance', 'Comedy']   
homepage                                                             NaN   
id                                                                 15602   
imdb_id                                                        tt0113228   
original_language                                                     en   
original_title                                          Grumpier Old Men   
overview               A family wedding reignites the ancient feud be...   
popularity                               

In [7]:
md['genres'] = md['genres'].apply(ast.literal_eval)

In [8]:
base_poster_url = 'http://image.tmdb.org/t/p/w185'
md['poster_path'] = "<img src='" + base_poster_url + md['poster_path'] + "' style='height:100px;'>"


In [9]:
md['poster_path']

0       <img src='http://image.tmdb.org/t/p/w185/rhIRb...
1       <img src='http://image.tmdb.org/t/p/w185/vzmL6...
2       <img src='http://image.tmdb.org/t/p/w185/6ksm1...
3       <img src='http://image.tmdb.org/t/p/w185/16XOM...
4       <img src='http://image.tmdb.org/t/p/w185/e64sO...
                              ...                        
9020    <img src='http://image.tmdb.org/t/p/w185/jcP3H...
9021    <img src='http://image.tmdb.org/t/p/w185/yWp7P...
9022    <img src='http://image.tmdb.org/t/p/w185/q1lrN...
9023    <img src='http://image.tmdb.org/t/p/w185/q2XVe...
9024    <img src='http://image.tmdb.org/t/p/w185/uv7sy...
Name: poster_path, Length: 9025, dtype: object

## Demographic Filtering - Weighted Rating

In [10]:
# IMDB Top Movies Chart Fomula : 
# WR = (v/(v+m).R) + (m/(v+m).C)
# v : số  lượng người bình chọn cho 1 bộ phim 
# m : số lượng bình chọn cần thiếu để được xét vào list - Một phim phải 
# có lượng vote > 95% các phim khác trong list
# R : rating  

In [11]:
vote_counts = md[md['vote_count'].notnull()]['vote_count']

In [12]:
vote_averages = md[md['vote_average'].notnull()]['vote_average']

In [13]:
# mean() function can be used to calculate 
# mean/average of a given list of numbers

C = vote_averages.mean()

In [14]:
# rating trung binh tren toan tap dataset
C

6.362227146814405

In [15]:
# Tính phân vị - tìm giá trị m sao cho 95% giá trị trong list bé hơn m
# 5% còn lại lớn hơn nó 
m = vote_counts.quantile(0.95)

In [16]:
m

2085.599999999995

In [17]:
qualified = md[(md['vote_count'] >= m) & (md['vote_count'].notnull()) 
            & (md['vote_average'].notnull())]

In [18]:
qualified = qualified[['poster_path','title','year','vote_count','vote_average','genres']]

In [19]:
qualified.shape

(452, 6)

In [20]:
# sumary : một phim cần phải đạt trên 434 votes để  được xét 
#        : điểm rating trung bình là 5.2 
#        : có 2274 phim đạt yêu cầu 

In [21]:
def weighted_rating(x,m,C):
    v = x['vote_count']
    R = x['vote_average']
    
    return (v/(m+v) * R) + (m/(m+v) * C)

In [22]:
qualified['wr'] = md.apply(lambda x: weighted_rating(x,m,C), axis=1)

In [22]:
# ascending : tăng dần 

qualified = qualified.sort_values('wr', ascending = False)

In [23]:
HTML(qualified.to_html(escape = False))

In [24]:
s = md.apply(lambda x: pd.Series(x['genres']),axis=1).stack().reset_index(level=1, drop=True)
s.name = 'genre'
gen_md = md.drop('genres', axis=1).join(s)

In [25]:
gen_md.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22321 entries, 0 to 9024
Data columns (total 26 columns):
adult                    22321 non-null bool
belongs_to_collection    4553 non-null object
budget                   22321 non-null int64
homepage                 4957 non-null object
id                       22321 non-null int64
imdb_id                  22321 non-null object
original_language        22321 non-null object
original_title           22321 non-null object
overview                 22298 non-null object
popularity               22321 non-null float64
poster_path              22314 non-null object
production_companies     22321 non-null object
production_countries     22321 non-null object
release_date             22321 non-null object
revenue                  22321 non-null float64
runtime                  22321 non-null float64
spoken_languages         22321 non-null object
status                   22317 non-null object
tagline                  17830 non-null object
ti

### Filter By Genre

In [26]:
def build_chart(genre, percentile):
    df = gen_md[gen_md['genre'] == genre]
    vote_counts = df[df['vote_count'].notnull()]['vote_count'].astype('int')
    vote_averages = df[df['vote_average'].notnull()]['vote_average'].astype('int')
    
    C = vote_averages.mean()
    m = vote_counts.quantile(percentile)
    
    qualified = df[(df['vote_count'] >= m) & (df['vote_count'].notnull()) & (df['vote_average'].notnull())]
    qualified = qualified[['poster_path','title','year','vote_count','vote_average','genre']]
    
    qualified['vote_count'] = qualified['vote_count'].astype('int')
    
    qualified['wr'] = qualified.apply(lambda x: weighted_rating(x,m,C), axis=1)
    
    qualified = qualified.sort_values('wr', ascending= False)
    
    return qualified



In [27]:
pop_gen = pd.DataFrame(gen_md['genre'].value_counts()).reset_index()
pop_gen.column = ['genre','movies']

In [28]:
list_genre =  pop_gen['index']
list_genre.shape

(20,)

In [29]:
HTML(build_chart(list_genre.loc[0],0.9).head(10).to_html(escape = False))

## Movie Description Based Recommender

In [10]:
def graph_result(result):
    md_graph = md[['poster_path','title','description','year','vote_count','vote_average']].copy()
    list_result_dataframe = []
     
    for i in result:
         list_result_dataframe.append(md_graph.iloc[i]) 

    list_result_dataframe = pd.DataFrame(list_result_dataframe)                
    return HTML(list_result_dataframe.to_html(escape = False))

### Content-Based By Title And Description Using Sklearn

In [17]:
md.description = md['description'].fillna('')

In [18]:
tf = TfidfVectorizer(analyzer='word',ngram_range=(1, 2),min_df=0, stop_words='english',use_idf=True)
tfidf_matrix = tf.fit_transform(md['description']+' '+md['title'])

In [19]:
tfidf_matrix.shape
# có 9099 vector tương ướng với 9099 overview,
# mỗi vector có 268124 chiều 

(9025, 281313)

In [20]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
# Compute the cosine similarity matrix

In [33]:
import scipy.sparse
scipy.sparse.save_npz('test_sparse.npz', cosine_sim)

AttributeError: 'numpy.ndarray' object has no attribute 'format'

In [21]:
cosine_sim.shape

(9025, 9025)

In [23]:
cosine_sim[0]

array([1.        , 0.00614994, 0.        , ..., 0.        , 0.        ,
       0.00598153])

In [24]:
cosine_sim[1]

array([0.00614994, 1.        , 0.01435999, ..., 0.        , 0.        ,
       0.00538877])

In [25]:
md = md.reset_index()
titles = md['title']
indices = pd.Series(md.index, index=md['title'])

In [26]:
indices

title
Toy Story                                                0
Jumanji                                                  1
Grumpier Old Men                                         2
Waiting to Exhale                                        3
Father of the Bride Part II                              4
                                                      ... 
Sharknado 4: The 4th Awakens                          9020
The Last Brickmaker in America                        9021
Rustom                                                9022
Mohenjo Daro                                          9023
The Beatles: Eight Days a Week - The Touring Years    9024
Length: 9025, dtype: int64

In [27]:
md[md['title'] == "The Avengers" ]

index  adult                              belongs_to_collection  \
1707   1707  False                                                NaN   
7839   7839  False  {'id': 86311, 'name': 'The Avengers Collection...   

         budget                                genres  \
1707   60000000                            [Thriller]   
7839  220000000  [Science Fiction, Action, Adventure]   

                               homepage     id    imdb_id original_language  \
1707                                NaN   9320  tt0118661                en   
7839  http://marvel.com/avengers_movie/  24428  tt0848228                en   

     original_title  ... runtime                          spoken_languages  \
1707   The Avengers  ...    89.0  [{'iso_639_1': 'en', 'name': 'English'}]   
7839   The Avengers  ...   143.0  [{'iso_639_1': 'en', 'name': 'English'}]   

        status                     tagline         title  video  vote_average  \
1707  Released  Saving the World in Style.  The Avengers  False           4.4   
7839  Released     Some assembly required.  The Avengers  False           7.4   

      vote_count                                        description  year  
1707       205.0  British Ministry agent John Steed, under direc...  1998  
7839     12000.0  When an unexpected enemy emerges and threatens...  2012  

[2 rows x 27 columns]

In [28]:
def get_recommendations(title):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:31]
    movie_indices = [i[0] for i in sim_scores]
    return titles.iloc[movie_indices]

In [29]:
get_recommendations('The Godfather').head(10)

973      The Godfather: Part II
8354                 The Family
3508                       Made
1581    The Godfather: Part III
4191         Johnny Dangerously
5651                       Fury
2411             American Movie
29               Shanghai Triad
7730              Henry's Crime
3287          Jaws: The Revenge
Name: title, dtype: object

In [30]:
def get_recommendations(k,title):
    # Get the index of the movie that matches the title
    idx = []
    idx.append(indices[title])
    print(idx)
    result = {}
    
    for i in idx:
                # Get the pairwsie similarity scores of all movies with that movie
                sim_scores = list(enumerate(cosine_sim[i]))

                # Sort the movies based on the similarity scores
                sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
                
                # Get the scores of the 10 most similar movies
                #(element number 0 is the movie it self)
                sim_scores = sim_scores[1:11]

                movie_indices = [k[0] for k in sim_scores]
                result[i,title] = movie_indices[:k]
                
    return result    

In [31]:
get_recommendations(10,'The Dark Knight')

[6873]


{(6873, 'The Dark Knight'): [7901,
  132,
  524,
  8196,
  2578,
  1113,
  8134,
  7537,
  7871,
  6125]}

In [32]:
result = get_recommendations(10,'The Dark Knight')
html = ""

for i in result:
        print(i[0]," - ",i[1])
        display(graph_result(result[i]))
        print("-------------------------------")   

[6873]
6873  -  The Dark Knight


-------------------------------


### Content-Based By Title And Description From Scatch

In [45]:
from ipynb.fs.full.Description_Title_Content_Base_Recommender import cosine_similarity_ver2
cosine_similarity_ver2(11,"The Dark Knight")

array([7901, 8134,  132, 8196, 6125, 2578, 1113,  524, 7871, 7537])

In [46]:
graph_result(list(cosine_similarity_ver2(11,"The Dark Knight")))

### User Vector

In [10]:
Yhat = np.load('tf_idf_pred_rating.npy')

In [11]:
len(Yhat)

9025

In [12]:
ratings_train = train[['userId','id','rating','movieIndex']]
ratings_matrix = ratings_train.values

In [13]:
# this fuction return movie_index in meta_data_dataset and ratings of user  
def get_items_rated_by_user(rate_matrix, user_id):
    y = rate_matrix[:,0] # get all the value in user_id column
    print(y)
    # get list of user_id index in y which value equal input 
    # user_id
    ids = np.where(y == user_id)[0]
    # get list movie_id matching user_id 
    item_ids = rate_matrix[ids, 3]
    item_ids = [int(i) for i in item_ids]
    
    scores = rate_matrix[ids,2]
    return (item_ids, scores)

In [14]:
def get_list_movie_have_not_rated(rate_matrix, userId,movie_count):
    user_rated, score = get_items_rated_by_user(rate_matrix,userId)
    result = []
    for i in range(movie_count):
         if i not in user_rated: result.append(i)
    return (userId, result)            

In [15]:
def TF_IDF_Content_Based_Recommender(rate_matrix, userId,movie_count):
    userId, list_not_rate =  get_list_movie_have_not_rated(rate_matrix, userId,movie_count)
    result = {}
    for i in list_not_rate:
        result[i] = Yhat[i, userId]
    
    result = sorted(result.items(), key=operator.itemgetter(1),reverse=True)
    result = dict(result)
    return result

In [16]:
def TF_IDF_Content_Based_Recommender2(rate_matrix, userId,movie_count):
    userId, list_not_rate =  get_list_movie_have_not_rated(rate_matrix, userId,movie_count)
    result = {}
    for i in list_not_rate:
        result[i] = Yhat[i, userId]
    
    result = dict(result)
    return result

## Metadata Based Recommender

### Merging cast crew keyword data into main dataframe

In [17]:
smd =  pd.read_csv('../the-movies-dataset/movies_metadata_merge_crew_keywords.csv')
graph = smd[['poster_path','title','year','vote_count','vote_average','genres']]

### Using Sklearn Library

In [18]:
from ipynb.fs.full.Cast_Director_Gernes_Content_Base_Recommender import  get_recommendations
result = get_recommendations("The Dark Knight",11)
for i in result:
    list_movie_result = result[i] 
graph_result(list_movie_result)    

KeyboardInterrupt: 

### From Scatch

In [ ]:
from ipynb.fs.full.Cast_Director_Gernes_Content_Base_Recommender import  get_recommendations_ver2

In [ ]:
result = get_recommendations_ver2("The Dark Knight",11)
for i in result:
    list_movie_result = result[i] 
graph_result(list_movie_result)    

## Collaborative Filtering 

In [19]:
f = open('KNN_Mean_predict_rating_result.pckl', 'rb')
KNN_predict_rating_result = pickle.load(f)
f.close()

In [20]:
type(KNN_predict_rating_result)

dict

In [21]:
user0 = {}
for i in KNN_predict_rating_result:
    if i[0] == 0: user0[i[1]] = KNN_predict_rating_result[i] 
len(user0)   

9010

In [22]:
def collaborative_fillter_recommender(userId,predict_rating_result):
    result = {}
    for i in predict_rating_result:
        if i[0] == userId:
            result[i[1]] = predict_rating_result[i]
    result = sorted(result.items(), key=operator.itemgetter(1),reverse=True)
    result = dict(result)
    return result       

## Hybrid recommender ver 1

In [23]:
def Hibrid_Recommender(user_id):
    const_x = 3
    content_based_list = TF_IDF_Content_Based_Recommender(ratings_matrix,user_id,N)
    collaborative_based_list = collaborative_fillter_recommender(user_id,KNN_predict_rating_result)
    hybrid_movie_list = collaborative_based_list
    
    #for i in collaborative_based_list:
          #collaborative_based_list[i] = content_based_list[i]*0.4 + collaborative_based_list[i]*0.6      
            #print(content_based_list[i],collaborative_based_list[i]) 
    print(len(content_based_list),len(collaborative_based_list))
    
    result = sorted(hybrid_movie_list.items(), key=operator.itemgetter(1),reverse=True)
    result = dict(result)
    return result

In [24]:
content_based_list = TF_IDF_Content_Based_Recommender(ratings_matrix,0,N)
collaborative_based_list = collaborative_fillter_recommender(0,KNN_predict_rating_result)

[  0.   0.   0. ... 670. 670. 670.]


In [25]:
TF_IDF_Content_Based_Recommender2(ratings_matrix,0,N)

[  0.   0.   0. ... 670. 670. 670.]


{0: 2.418331634215756,
 1: 2.420680837319464,
 2: 2.4215696422827664,
 3: 2.4241181973381685,
 4: 2.421797526304559,
 5: 2.4321669349767925,
 6: 2.421830450323965,
 7: 2.4229540676386176,
 8: 2.427536708988026,
 9: 2.409453117788023,
 10: 2.4192513080059443,
 11: 2.519410224120131,
 12: 2.422810951430595,
 13: 2.4235431003379446,
 14: 2.4171652114399365,
 15: 2.4215741004774776,
 16: 2.4306164505891616,
 17: 2.421810153803982,
 18: 2.418055729896069,
 19: 2.4151163703778016,
 20: 2.424113141344164,
 21: 2.4201186751147024,
 22: 2.4200810497560528,
 23: 2.423375484610004,
 24: 2.4243058135492177,
 25: 2.4242273168457222,
 26: 2.4182664774249734,
 27: 2.422278026192373,
 28: 2.406855768880845,
 29: 2.4200388175282646,
 31: 2.4230478979753483,
 32: 2.420679001589983,
 33: 2.4215577087735505,
 34: 2.4269139723909308,
 35: 2.397423427978889,
 36: 2.4152693672841337,
 37: 2.4169555949039836,
 38: 2.4214540237857416,
 39: 2.4206792407851885,
 40: 2.4234246209910646,
 41: 2.4188762045151453,
 

In [85]:
list_movie = []
for i in content_based_list:
    list_movie.append(i)
len(list_movie)    

8962

### Content Based

In [81]:
list_movie = []
for i in content_based_list:
    list_movie.append(i)
graph_result(list_movie[0:10])  

In [82]:
len(list_movie)

9011

### Collaborative

In [62]:
list_movie = []
for i in collaborative_based_list:
    list_movie.append(i)
graph_result(list_movie[0:10])  

### Hybrid 

In [63]:
result = Hibrid_Recommender(0)

9011 9010


In [36]:
list_movie = []
for i in result:
    list_movie.append(i)
graph_result(list_movie[0:10])  

NameError: name 'result' is not defined

In [34]:
9025 - 14

9011